import { MetadataRoute } from "next"

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://xcoin-website.vercel.app"

  const routes = [
    "",
    "/overview",
    "/develop",
    "/fund",
    "/docs",
    "/faq",
    "/community",
    "/privacy",
    "/quantum-safe",
    "/scalability",
    "/governance",
    "/roadmap",
    "/network",
    "/member",
    "/contributor",
    "/validator",
    "/legal",
    "/what-is-wots-plus",
    "/what-is-sphincs-plus",
    "/what-is-zk-starks",
    "/what-are-view-keys",
    "/what-is-aes-512",
    "/what-is-stealth-addresses",
    "/what-is-xxx-dao",
    "/what-is-dag-plus",
    "/what-is-zk-rollups",
    "/how-xcoin-handles-10000-tps",
    "/what-is-halo-2",
    "/what-is-poseidon-hash",
    "/what-is-ring-signature",
    "/what-is-sep",
    "/what-is-genesis-block",
    "/what-are-xxx-tokens",
    "/what-is-fixed-supply",
    "/validator-application",
    "/learning",
    "/what-is-privacy-by-default",
    "/how-xcoin-scales-without-mining",
    "/what-is-keccak-512",
    "/how-voting-and-proposals-work",
    "/who-holds-power-in-the-ecosystem",
    "/treasury-delegation-and-validator-licenses",
    "/your-role-as-a-token-holder",
    "/using-xcoin-for-payments-and-savings",
    "/anonymous-donations-remittances-and-business-transfers",
    "/eco-friendly-infrastructure",
    "/participate-in-governance",
    "/stay-updated",
    "/why-xcoin-uses-no-mining",
    "/why-xcoin-replaces-bitcoin",
    "/why-xcoin-is-better",
    "/crowdfunding",
    "/the-man-in-the-background",
    "/what-is-xxx-blockchain",
    "/optional-compliance",
    "/the-rise-of-validators",
    "/philosophy-behind-anonymous-finance",
    "/the-power-of-xxx-dao-members",
    "/power-in-the-hands-of-the-community",
    "/see-whats-coming",
    "/cryptographic-building-blocks",
    "/what-is-no-trusted-setup",
  ]

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "weekly" : "monthly",
    priority: route === "" ? 1 : 0.8,
  }))
}

