#!/bin/bash

# Manuelles SSH-Setup - führt dich durch den Prozess

echo "🔑 SSH-Key Setup für Xcoin Server"
echo "=================================="
echo ""
echo "Schritt 1: Public Key anzeigen"
echo "--------------------------------"
echo ""
cat ~/.ssh/id_rsa.pub
echo ""
echo ""
echo "Schritt 2: SSH zum Server verbinden"
echo "-----------------------------------"
echo "Führe diesen Befehl aus:"
echo "  ssh Xcoin@82.221.100.116"
echo ""
echo "Passwort: FLduSONDedfRfsw52g3jfD93SsFfs!"
echo ""
echo "Schritt 3: Auf dem Server ausführen"
echo "-----------------------------------"
echo "Nach erfolgreicher Verbindung, führe diese Befehle auf dem Server aus:"
echo ""
echo "  mkdir -p ~/.ssh"
echo "  chmod 700 ~/.ssh"
echo "  nano ~/.ssh/authorized_keys"
echo ""
echo "Dann kopiere den Public Key (siehe oben) in die Datei, speichere mit Ctrl+O, Enter, Ctrl+X"
echo ""
echo "Dann:"
echo "  chmod 600 ~/.ssh/authorized_keys"
echo "  exit"
echo ""
echo "Schritt 4: Test"
echo "--------------"
echo "Teste die Verbindung:"
echo "  ssh Xcoin@82.221.100.116"
echo ""
echo "Wenn es ohne Passwort funktioniert, war das Setup erfolgreich!"
echo ""
